### ISSUE TITLE
Organization members are unable to push upstream.

### ISSUE THREAD

**Issue by kWhittington** [UNO-IGDA/PlaceholderProject#1]
Contributors are unable to push upstream to this repo at this time:

```
ERROR: Permission to UNO-IGDA/PlaceholderProject.git denied to kWhittington.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So far, only contributors with the "member" role have reported this issue. Since there are no other owners, @HeLooksAngry will need to debug this problem.

**Comment by HeLooksAngry** [comment]
@kWhittington  @poker158149  @bkruebbe 
Changed member settings for the organization. Was previously set to read, and only allowed pull/clone requests. 

It's now set to Write, which should allow all members to clone, pull, and push to Organization repos.
Leaving issue open for members to close when they can successfully push to a repo.

**Comment by kWhittington** [comment]
I was able to successfully push a new branch upstream: https://github.com/UNO-IGDA/PlaceholderProject/tree/chore/confirm_members_can_push_upstream

**Comment by kWhittington** [comment]
and I was able to successfully push to master: https://github.com/UNO-IGDA/PlaceholderProject/commit/d8455d8c17aacc4bdc43f99870b814b21c17015d

**Comment by kWhittington** [comment]
I'm going to close this issue. If anyone else continues to have trouble, we can reopen it.
