### ISSUE TITLE
Integrate New Character Controller script to Player Object

### ISSUE THREAD

**Issue by HeLooksAngry** [UNO-IGDA/PlaceholderProject#4]
The current Character controller script is extremely rudimentary. Replace the current script with 
the more robust one mentioned in the meeting.

**Comment by parkersprouse** [comment]
I pushed the new controller script to the branch `feature/controllers/player_controller`. I removed the old player controller script and added two new ones. One of them is a motor script that takes care of player input and passes the calculated movement to a `Move()` function inside of the collision script, which is the second script. The collision script uses raycasts to check for vertical and horizontal collisions along a specific layer or layers.

**Comment by HeLooksAngry** [comment]
Looks (and feels) good. I'm closing this issue. Good stuff.
