### ISSUE TITLE
Remove `JumpKicker` folder from root directory.

### ISSUE THREAD

**Issue by kWhittington** [UNO-IGDA/PlaceholderProject#6]
Is there a specific reason why we have two root directories?

Our root directory should be what `JumpKicker` is. So we really want `JumpKicker`'s contents in our root directory and not have to jump through an extra directory.

We can also move this to a repo named "JumpKicker", too.

**Comment by parkersprouse** [comment]
I agree with this, but is there a way we can do it without needing to create a new repo? I guess we could simply move the files up a directory on our local machines and push like that, but that could mess up the project from being seen as a Unity project. I've never gone back and changed the file structure of a project before, so I'm not sure how that would affect things.

**Comment by kWhittington** [comment]
I'll base off of `master` and see what's up.
